
name: 'Upload a Build Artifact'
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: sudo apt install doxygen

    - run: doxygen -g

    - run: doxygen

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: Doxyfile  
  