name: send message
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

    - uses: Stefan19K/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        message: The ${{ github.event_name }} event triggered first step.
